### PR TITLE
Added change to give the user the option of enforcing return types for anonymous functions

### PR DESCRIPTION
**Pull request by qwertykg**
Added change to give the user the option of enforcing return types for anonymous functions to allow users to disable return types for anonymous functions they have to set enforceReturnTypeForAnonymous = false

### CODE REVIEW

**Comment by adireddy** [comment]
Can you also add a test to cover this, please?

**Comment by AlexHaxe** [comment]
Also please fix checkstyle issues introduced by your changes.

**Comment by Gama11** [comment]
I feel like `false` would be a more sensible default value, especially considering `enforceReturnType` already defaults to `false`.

**Comment by qwertykg** [comment]
Hi sorry guys, I need to move this pull request, will create a new one ASAP

**Pull request closed without merging**
